version: "3.3"
services:
  nginx:
    image: "nginx:alpine"
    ports:
      - "80:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"

  traefik:
    image: "traefik:v2.4"
    container_name: "traefik"
    command:
      # - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8081:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  auth:
    build: ./services/authentication_svc
    container_name: "auth"
    environment:
      REDIS_ADDRESS: redis
      REDIS_DATABASE: 3
      SECRET_KEY: changeme
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth.rule=PathPrefix(`/users`)"
      - "traefik.http.routers.auth.entrypoints=web"

  shortener:
    container_name: "shortener"
    build: ./services/shortener_svc
    environment:
      REDIS_ADDRESS: redis
      SECRET_KEY: changeme
      PERSIST: "yes"
      CLEAN_DATABASE: "yes"
      REDIS_DATABASE: 0
      REDIS_USER_DATABASE: 1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shortener.rule=PathPrefix(`/`)"
      - "traefik.http.routers.shortener.entrypoints=web"

  redis:
    image: redis:alpine
    ports:
    - 6379:6379
