{{- $fullName := include "shortener.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shortener.fullname" . }}
  labels:
    {{- include "shortener.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "shortener.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "shortener.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shortener.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          env:
          - name: REDIS_ADDRESS
            value: "{{ .Values.redis.address }}"
          - name: REDIS_DATABASE
            value: "{{ .Values.redis.database }}"
          - name: REDIS_USER_DATABASE
            value: "{{ .Values.redis.userDatabase }}"
          - name: PERSIST
            value: "{{ .Values.redis.persist }}"
          - name: CLEAN_DATABASE
            value: "{{ .Values.redis.clean }}"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key:  secretKey
                {{- if eq .Values.secretKey.existingSecret "" }}
                name: {{ $fullName }}-secret-key
                {{else}}
                name: {{ .Values.secretKey.existingSecret }}
                {{- end}}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
