{{- $fullName := include "shortener.fullname" . -}}
{{- if .Values.ingress.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ $fullName }}
spec:
  hosts:
  - "*"
  gateways:
  {{- toYaml .Values.ingress.gateways | nindent 2 }}
  http:
  - match:
    {{- toYaml .Values.ingress.match | nindent 4 }}
    {{- if .Values.ingress.rewrite }}
    rewrite:
    {{- toYaml .Values.ingress.rewrite | nindent 6 }}
    {{- end }}
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ .Values.service.port }}
    corsPolicy:
      allowCredentials: true
      allowOrigin:
        - "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - authorization
        - x-access-token
        - content-type
{{- end }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ $fullName }}
spec:
  host: {{ $fullName }}
  trafficPolicy:
    loadBalancer:
      simple: {{ .Values.service.lbPolicy }}
    connectionPool:
      http:
        idleTimeout: 0.01s
