{{- $fullName := include "shortener.fullname" . -}}
{{- if eq .Values.secretKey.existingSecret "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-secret-key
stringData:
  secretKey: {{ .Values.secretKey.value | default "" | quote }}
{{- end}}
