apiVersion: v1
kind: Service
metadata:
  name: {{ include "shortener.fullname" . }}
  labels:
    {{- include "shortener.labels" . | nindent 4 }}
spec:
  clusterIP: ""
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shortener.selectorLabels" . | nindent 4 }}
