version: "3.3"
services:
  shortener:
    build: .
    ports:
      - 127.0.0.1:5000:80
    environment:
      REDIS_ADDRESS: redis
      PERSIST: "yes"
      CLEAN_DATABASE: "yes"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
