apiVersion: v2
name: url-shortener
description: url shortener service composed of multiple microservices

type: application

version: 0.1.0

appVersion: "1.16.0"

icon: "https://user-images.githubusercontent.com/19824574/41482054-47a3a702-70a2-11e8-9561-de51c5f71220.png"

dependencies:
  - name: "authentication"
  - name: "shortener"
    # version: ">=0.1.0"
  - name: redis
    version: ">=6.2.2"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
