name: build

on: [ push, pull_request ]

jobs:
  import:
    name: import ${{ matrix.package.repo }}
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        package:
          - name: preprocessing
            repo: yaaani85/wscbs2021-preprocessing
          - name: training
            repo: yaaani85/wscbs2021-training
          - name: predicting
            repo: yaaani85/wscbs2021-predicting
          - name: kaggle
            repo: romnn/kaggle-brane
    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Install brane CLI
      uses: romnn/setup-brane-action@master

    - name: Import brane package
      shell: bash
      run: |
        sudo $HOME/.local/bin/brane import ${{ matrix.package.repo }}
        (set -o pipefail && echo "import ${{ matrix.package.name }};" | sudo $HOME/.local/bin/brane repl -c)
